# Generated by Django 5.2.6 on 2025-09-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('OPERADOR', 'Operador'), ('TECNICO', 'Técnico')], default='OPERADOR', max_length=20),
        ),
    ]
