# Generated by Django 5.2.6 on 2025-09-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('OPERADOR', 'Operador'), ('TECNICO', 'Técnico')], default='OPERADOR', max_length=20),
        ),
    ]
