# Generated by Django 5.2.6 on 2025-09-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_role_alter_customuser_nombre_rol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='rol',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('OPERADOR', 'Operador'), ('TECNICO', 'Técnico')], default='OPERADOR', max_length=20),
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
